"""Contract tests for ``code/tools/verify_torch_groups.sh``.

Hermetic: every test runs the real script against a **stub ``uv``** placed first
on ``PATH``, so nothing resolves, downloads, installs, or reads the committed
``uv.lock``. The only files written are inside pytest's ``tmp_path`` (the stub,
its fixture, its invocation log, and the throwaway uv cache directory the script
creates under a redirected ``TMPDIR``). No shared, persistent cache is touched.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

import pytest


ROOT = Path(__file__).resolve().parents[2]
VERIFY_TORCH_GROUPS = ROOT / "code" / "tools" / "verify_torch_groups.sh"
# Resolved against the real PATH: the tests hand the script a doctored PATH.
BASH = shutil.which("bash")

pytestmark = pytest.mark.skipif(BASH is None, reason="bash is required to run the verifier")

STUB_UV = '''#!{python}
"""Stand in for uv: answer from a JSON fixture and record every invocation."""
import json
import os
import sys
from pathlib import Path

argv = sys.argv[1:]
fixture = json.loads(Path(os.environ["STUB_UV_FIXTURE"]).read_text(encoding="utf-8"))
with Path(os.environ["STUB_UV_LOG"]).open("a", encoding="utf-8") as handle:
    handle.write(json.dumps(argv) + "\\n")


def emit(entry):
    sys.stdout.write(entry.get("stdout", ""))
    sys.stderr.write(entry.get("stderr", ""))
    raise SystemExit(int(entry.get("returncode", 0)))


if "lock" in argv:
    emit(fixture.get("lock", {{"returncode": 0}}))
if "export" in argv:
    group = argv[argv.index("--group") + 1]
    fmt = argv[argv.index("--format") + 1] if "--format" in argv else "requirements.txt"
    section = "pylock" if fmt == "pylock.toml" else "exports"
    entry = fixture.get(section, {{}}).get(group)
    if entry is None:
        emit({{
            "returncode": 2,
            "stderr": "error: no " + section + " fixture for group " + group + chr(10),
        }})
    emit(entry)
emit({{"returncode": 2, "stderr": "error: unexpected uv invocation " + json.dumps(argv) + chr(10)}})
'''

ROCM_EXPORT = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --group rocm --no-hashes
-e .
numpy==2.5.1 ; python_full_version == '3.12.*' and sys_platform == 'linux'
sentence-transformers==5.6.0 ; python_full_version == '3.12.*'
torch @ https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.1/torch-2.9.1%2Brocm7.2.1.lw.gitff65f5bc-cp312-cp312-linux_x86_64.whl ; python_full_version == '3.12.*'
transformers==5.13.0 ; python_full_version == '3.12.*'
triton @ https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.1/triton-3.5.1%2Brocm7.2.1.gita272dfa8-cp312-cp312-linux_x86_64.whl ; python_full_version == '3.12.*'
"""

NVIDIA_RUNTIME_LINES = """\
nvidia-cublas-cu12==12.8.4.1 ; python_full_version == '3.12.*' and platform_machine == 'x86_64'
nvidia-cuda-nvrtc-cu12==12.8.93 ; python_full_version == '3.12.*' and platform_machine == 'x86_64'
nvidia-cuda-runtime-cu12==12.8.90 ; python_full_version == '3.12.*' and platform_machine == 'x86_64'
nvidia-cudnn-cu12==9.10.2.21 ; python_full_version == '3.12.*' and platform_machine == 'x86_64'
nvidia-nccl-cu12==2.27.5 ; python_full_version == '3.12.*' and platform_machine == 'x86_64'
"""


def _cuda_export(torch_line: str, *, nvidia_runtime: bool = True) -> str:
    body = [
        "# This file was autogenerated by uv via the following command:",
        "#    uv export --frozen --group cuda --no-hashes",
        "-e .",
        "numpy==2.5.1 ; python_full_version == '3.12.*' and sys_platform == 'linux'",
        "sentence-transformers==5.6.0 ; python_full_version == '3.12.*'",
        torch_line,
        "transformers==5.13.0 ; python_full_version == '3.12.*'",
    ]
    if nvidia_runtime:
        body.extend(NVIDIA_RUNTIME_LINES.splitlines())
    return "\n".join(body) + "\n"


GOOD_CUDA_TORCH = "torch==2.9.1 ; python_full_version == '3.12.*' and sys_platform == 'linux'"

# The PEP 751 rendering of the same export. Unlike a requirements line, it
# records the index each package was resolved from, which is the only thing that
# can tell `torch==2.9.1` from PyPI apart from `torch==2.9.1` from a mirror.
PYLOCK_HEADER = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --group cuda --format pylock.toml
lock-version = "1.0"
created-by = "uv"
requires-python = "==3.12.*"

[[packages]]
name = "numpy"
version = "2.5.1"
index = "https://pypi.org/simple"
wheels = [
    { name = "numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.whl", url = "https://files.pythonhosted.org/packages/aa/numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.whl", hashes = { sha256 = "1111" } },
]
"""

PYPI_INDEX = "https://pypi.org/simple"


def _torch_pylock_package(
    *,
    version: str = "2.9.1",
    index: str | None = PYPI_INDEX,
    wheel_url: str = (
        "https://files.pythonhosted.org/packages/bb/"
        "torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl"
    ),
    subtable_wheels: bool = False,
) -> str:
    """One `[[packages]]` block for torch, rendered the way uv renders them.

    ``index=None`` is what a direct-URL wheel looks like: no index key at all.
    ``subtable_wheels`` switches the wheel list from an inline array to
    ``[[packages.wheels]]`` sub-tables, whose own column-0 ``name`` key must not
    be read as the package's name.
    """
    wheel_name = f"torch-{version}-cp312-cp312-manylinux_2_28_x86_64.whl"
    lines = ["[[packages]]", 'name = "torch"', f'version = "{version}"']
    if index is not None:
        lines.append(f'index = "{index}"')
    if subtable_wheels:
        lines.extend(
            [
                "",
                "[[packages.wheels]]",
                f'name = "{wheel_name}"',
                f'url = "{wheel_url}"',
                'hashes = { sha256 = "2222" }',
            ]
        )
    else:
        lines.extend(
            [
                "wheels = [",
                f'    {{ name = "{wheel_name}", url = "{wheel_url}", '
                'hashes = { sha256 = "2222" } },',
                "]",
            ]
        )
    return "\n".join(lines) + "\n"


def _cuda_pylock(*torch_packages: str) -> str:
    packages = torch_packages or (_torch_pylock_package(),)
    return PYLOCK_HEADER + "\n" + "\n".join(packages)


# uv's own wording when the committed lock cannot serve the request.
STALE_LOCK_CHECK_ERROR = (
    "error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. "
    "To update the lockfile, run `uv lock`.\n"
)
STALE_EXPORT_ERROR = (
    "error: The lockfile at `uv.lock` needs to be updated, but `--frozen` was provided. "
    "To update the lockfile, run `uv lock`.\n"
)


class Result:
    """A completed verifier run plus the uv invocations it made."""

    def __init__(self, process: subprocess.CompletedProcess[str], invocations: list[list[str]]):
        self.returncode = process.returncode
        self.stdout = process.stdout
        self.stderr = process.stderr
        self.invocations = invocations

    @property
    def output(self) -> str:
        return self.stdout + self.stderr

    def subcommands(self) -> list[str]:
        """The uv subcommand of each invocation, ignoring the global flags."""
        found = []
        for argv in self.invocations:
            skip_value = False
            for token in argv:
                if skip_value:
                    skip_value = False
                    continue
                if token == "--cache-dir":
                    skip_value = True
                    continue
                if not token.startswith("-"):
                    found.append(token)
                    break
        return found


def _run_verifier(tmp_path: Path, fixture: dict[str, object]) -> Result:
    stub_dir = tmp_path / "stub-bin"
    stub_dir.mkdir()
    stub = stub_dir / "uv"
    stub.write_text(STUB_UV.format(python=sys.executable), encoding="utf-8")
    stub.chmod(0o755)

    fixture_path = tmp_path / "fixture.json"
    fixture_path.write_text(json.dumps(fixture), encoding="utf-8")
    log_path = tmp_path / "uv-invocations.jsonl"

    scratch_tmp = tmp_path / "scratch-tmp"
    scratch_tmp.mkdir()

    env = dict(os.environ)
    env["PATH"] = f"{stub_dir}{os.pathsep}{env.get('PATH', '')}"
    env["STUB_UV_FIXTURE"] = str(fixture_path)
    env["STUB_UV_LOG"] = str(log_path)
    # Any cache directory the script creates lands here, not in a shared one.
    env["TMPDIR"] = str(scratch_tmp)

    process = subprocess.run(
        [BASH, str(VERIFY_TORCH_GROUPS)],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    logged = log_path.read_text(encoding="utf-8") if log_path.exists() else ""
    invocations = [json.loads(line) for line in logged.splitlines() if line.strip()]
    return Result(process, invocations)


def _fixture(
    *,
    lock: dict[str, object] | None = None,
    rocm: dict[str, object] | None = None,
    cuda: dict[str, object] | None = None,
    cuda_pylock: dict[str, object] | None = None,
) -> dict[str, object]:
    return {
        "lock": lock if lock is not None else {"returncode": 0},
        "exports": {
            "rocm": rocm if rocm is not None else {"returncode": 0, "stdout": ROCM_EXPORT},
            "cuda": (
                cuda
                if cuda is not None
                else {"returncode": 0, "stdout": _cuda_export(GOOD_CUDA_TORCH)}
            ),
        },
        # Only the cuda group's source is proved this way, so the rocm group has
        # no pylock fixture: if the script ever asked for one, the stub would
        # fail the run instead of quietly answering.
        "pylock": {
            "cuda": (
                cuda_pylock
                if cuda_pylock is not None
                else {"returncode": 0, "stdout": _cuda_pylock()}
            ),
        },
    }


def test_both_groups_pass_on_the_intended_torch_builds(tmp_path: Path) -> None:
    result = _run_verifier(tmp_path, _fixture())

    assert result.returncode == 0, result.output
    assert "OK   uv.lock is current with pyproject.toml" in result.stdout
    assert "OK   rocm: torch @ https://repo.radeon.com/" in result.stdout
    assert "OK   cuda: torch==2.9.1 from https://pypi.org/simple" in result.stdout
    assert "Both hardware groups select their intended torch source." in result.stdout


def test_lock_currency_is_proved_without_installing(tmp_path: Path) -> None:
    """Currency comes from `uv lock --check`, and nothing may install."""
    result = _run_verifier(tmp_path, _fixture())

    assert result.subcommands() == ["lock", "export", "export", "export"]
    lock_argv = result.invocations[0]
    assert "--check" in lock_argv
    installing = {"sync", "add", "remove", "pip", "run", "tool", "build", "install"}
    assert not installing.intersection(result.subcommands())
    for argv in result.invocations[1:]:
        assert "--frozen" in argv, argv


def test_no_uv_call_may_provision_an_interpreter(tmp_path: Path) -> None:
    """The interpreter is the one install `--no-cache` alone would not prevent.

    This project pins Python 3.12.13. On a host without it, `uv lock` will fetch
    and install a managed interpreter just to resolve — silently, and outside
    the throwaway cache directory. `--no-python-downloads` turns that into a
    loud failure, which is what makes "installs nothing" true rather than true
    only on hosts that happen to already have the pinned Python.
    """
    result = _run_verifier(tmp_path, _fixture())

    assert result.invocations, "the verifier made no uv calls"
    for argv in result.invocations:
        assert "--no-python-downloads" in argv, argv


def test_the_cuda_source_proof_reads_a_group_scoped_pylock_export(tmp_path: Path) -> None:
    """Source comes from PEP 751 metadata scoped to the group, not from uv.lock."""
    result = _run_verifier(tmp_path, _fixture())

    pylock_calls = [argv for argv in result.invocations if "--format" in argv]
    assert len(pylock_calls) == 1, result.invocations
    argv = pylock_calls[0]
    assert argv[argv.index("--format") + 1] == "pylock.toml"
    # Scoped to cuda: an unscoped multi-fork uv.lock block is not what is parsed.
    assert argv[argv.index("--group") + 1] == "cuda"
    assert "--frozen" in argv
    assert "--no-cache" in argv
    assert "--no-python-downloads" in argv
    assert not any("uv.lock" in token for token in argv), argv


def test_every_uv_call_avoids_the_persistent_cache(tmp_path: Path) -> None:
    result = _run_verifier(tmp_path, _fixture())

    for argv in result.invocations:
        assert "--no-cache" in argv, argv
        cache_dir = Path(argv[argv.index("--cache-dir") + 1])
        assert tmp_path in cache_dir.parents, cache_dir
        assert cache_dir.name.startswith("verify-torch-groups-uv-cache."), cache_dir
    # The throwaway cache directory does not survive the run.
    leftovers = [
        entry
        for entry in (tmp_path / "scratch-tmp").iterdir()
        if entry.name.startswith("verify-torch-groups-uv-cache.")
    ]
    assert leftovers == []


def test_a_stale_lock_fails_before_any_export(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(lock={"returncode": 2, "stderr": STALE_LOCK_CHECK_ERROR}),
    )

    assert result.returncode == 1
    assert "FAIL uv.lock is stale" in result.stderr
    assert "needs to be updated" in result.stderr
    # A diagnosed stale lock is the one case where regenerating it is the fix.
    assert "Regenerate the lock with 'uv lock'" in result.stderr
    assert result.subcommands() == ["lock"]


def test_a_cpu_wheel_url_is_rejected(tmp_path: Path) -> None:
    cpu_url = (
        "torch @ https://download.pytorch.org/whl/cpu/"
        "torch-2.9.1%2Bcpu-cp312-cp312-linux_x86_64.whl ; python_full_version == '3.12.*'"
    )
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 0, "stdout": _cuda_export(cpu_url, nvidia_runtime=False)}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: expected torch==2.9.1 from PyPI, got a CPU-only wheel:" in result.stderr
    assert "OK   rocm:" in result.stdout


def test_a_non_radeon_direct_url_is_rejected(tmp_path: Path) -> None:
    """Even a CUDA-flavoured index is not the PyPI pin the group declares."""
    cuda_url = (
        "torch @ https://download.pytorch.org/whl/cu128/"
        "torch-2.9.1%2Bcu128-cp312-cp312-linux_x86_64.whl ; python_full_version == '3.12.*'"
    )
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 0, "stdout": _cuda_export(cuda_url)}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: expected the PyPI pin torch==2.9.1, got a direct URL:" in result.stderr


def test_a_rocm_wheel_in_the_cuda_group_is_rejected(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 0, "stdout": ROCM_EXPORT}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: expected torch==2.9.1 from PyPI, got the ROCm wheel:" in result.stderr


def test_a_wrong_torch_version_is_rejected(tmp_path: Path) -> None:
    wrong = "torch==2.8.0 ; python_full_version == '3.12.*' and sys_platform == 'linux'"
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 0, "stdout": _cuda_export(wrong)}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: expected exactly torch==2.9.1, got:" in result.stderr
    assert "torch==2.8.0" in result.stderr


def test_the_right_version_without_nvidia_runtime_deps_is_rejected(tmp_path: Path) -> None:
    """A CPU build published under the same version has no NVIDIA dependencies."""
    result = _run_verifier(
        tmp_path,
        _fixture(
            cuda={
                "returncode": 0,
                "stdout": _cuda_export(GOOD_CUDA_TORCH, nvidia_runtime=False),
            }
        ),
    )

    assert result.returncode == 1
    assert "resolves without the NVIDIA runtime packages" in result.stderr
    for package in ("nvidia-cuda-runtime", "nvidia-cublas", "nvidia-cudnn"):
        assert package in result.stderr


def test_an_alternate_registry_torch_is_rejected(tmp_path: Path) -> None:
    """The false positive the requirements line cannot catch.

    A mirror, a private devpi, or a torch-specific index all render as the same
    `torch==2.9.1` requirement. Only the source-bearing export separates them.
    """
    mirror = "https://mirror.internal.example.com/simple"
    result = _run_verifier(
        tmp_path,
        _fixture(
            cuda_pylock={
                "returncode": 0,
                "stdout": _cuda_pylock(_torch_pylock_package(index=mirror)),
            }
        ),
    )

    assert result.returncode == 1
    # The requirements export was the passing one, NVIDIA runtime deps and all.
    assert "OK   cuda:" not in result.stdout
    assert f"FAIL cuda: torch 2.9.1 resolves from {mirror}, not https://pypi.org/simple" in (
        result.stderr
    )


def test_a_pylock_entry_without_an_index_is_rejected(tmp_path: Path) -> None:
    """No index key at all is how a direct-URL wheel is recorded."""
    result = _run_verifier(
        tmp_path,
        _fixture(
            cuda_pylock={
                "returncode": 0,
                "stdout": _cuda_pylock(
                    _torch_pylock_package(
                        index=None,
                        wheel_url=(
                            "https://download.pytorch.org/whl/cu128/"
                            "torch-2.9.1-cp312-cp312-linux_x86_64.whl"
                        ),
                    )
                ),
            }
        ),
    )

    assert result.returncode == 1
    assert "records no index for torch 2.9.1" in result.stderr
    assert "https://pypi.org/simple" in result.stderr


def test_a_pylock_version_mismatch_is_rejected(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(
            cuda_pylock={
                "returncode": 0,
                "stdout": _cuda_pylock(_torch_pylock_package(version="2.9.0")),
            }
        ),
    )

    assert result.returncode == 1
    assert "selects torch 2.9.0, not 2.9.1" in result.stderr


def test_a_pylock_export_without_torch_is_rejected(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(cuda_pylock={"returncode": 0, "stdout": PYLOCK_HEADER}),
    )

    assert result.returncode == 1
    assert "names no torch package" in result.stderr


def test_two_torch_entries_in_the_pylock_export_are_rejected(tmp_path: Path) -> None:
    """One group-scoped export must select exactly one torch; ambiguity fails."""
    result = _run_verifier(
        tmp_path,
        _fixture(
            cuda_pylock={
                "returncode": 0,
                "stdout": _cuda_pylock(
                    _torch_pylock_package(),
                    _torch_pylock_package(version="2.9.1+rocm7.2.1", index=None),
                ),
            }
        ),
    )

    assert result.returncode == 1
    assert "expected one torch package in the pylock.toml export, got 2" in result.stderr


def test_subtable_style_pylock_wheels_do_not_confuse_the_parser(tmp_path: Path) -> None:
    """`[[packages.wheels]]` has its own column-0 `name`; it is not the package's."""
    result = _run_verifier(
        tmp_path,
        _fixture(
            cuda_pylock={
                "returncode": 0,
                "stdout": _cuda_pylock(_torch_pylock_package(subtable_wheels=True)),
            }
        ),
    )

    assert result.returncode == 0, result.output
    assert "OK   cuda: torch==2.9.1 from https://pypi.org/simple" in result.stdout


def test_a_stale_pylock_export_reports_the_lock(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(cuda_pylock={"returncode": 2, "stderr": STALE_EXPORT_ERROR}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: uv.lock does not carry this group." in result.stderr
    assert "Regenerate the lock with 'uv lock'" in result.stderr


def test_an_unrelated_pylock_export_failure_is_not_blamed_on_the_group(tmp_path: Path) -> None:
    unsupported = "error: unexpected value 'pylock.toml' for '--format <FORMAT>'\n"
    result = _run_verifier(
        tmp_path,
        _fixture(cuda_pylock={"returncode": 2, "stderr": unsupported}),
    )

    assert result.returncode == 1
    assert (
        "FAIL cuda: uv export --format pylock.toml failed for a reason unrelated to this group."
        in result.stderr
    )
    assert "unexpected value 'pylock.toml'" in result.stderr
    assert "does not carry this group" not in result.stderr
    assert "Regenerate the lock" not in result.stderr


def test_a_stale_export_reports_the_lock_and_uvs_own_error(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 2, "stderr": STALE_EXPORT_ERROR}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: uv.lock does not carry this group." in result.stderr
    assert "needs to be updated" in result.stderr
    assert "Regenerate the lock with 'uv lock'" in result.stderr


def test_an_undefined_group_reports_the_lock_and_uvs_own_error(tmp_path: Path) -> None:
    undefined = (
        "error: Group `cuda` is not defined in the project's `dependency-groups` table\n"
    )
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 2, "stderr": undefined}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: uv.lock does not carry this group." in result.stderr
    assert "is not defined in the project's `dependency-groups` table" in result.stderr


def test_an_unrelated_uv_failure_is_not_blamed_on_the_group(tmp_path: Path) -> None:
    network_error = (
        "error: Failed to fetch `https://pypi.org/simple/torch/`\n"
        "  Caused by: Connection refused (os error 111)\n"
    )
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 2, "stderr": network_error}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: uv export failed for a reason unrelated to this group." in result.stderr
    assert "Connection refused (os error 111)" in result.stderr
    assert "does not carry this group" not in result.stderr


@pytest.mark.parametrize(
    ("label", "stderr"),
    [
        ("unsupported flag", "error: unexpected argument '--check' found\n"),
        (
            "authentication",
            "error: Failed to fetch `https://pypi.org/simple/torch/`\n"
            "  Caused by: HTTP status client error (401 Unauthorized)\n",
        ),
        (
            "network",
            "error: Failed to fetch `https://pypi.org/simple/torch/`\n"
            "  Caused by: dns error: failed to lookup address information\n",
        ),
    ],
)
def test_an_unverifiable_lock_is_not_reported_as_stale(
    tmp_path: Path, label: str, stderr: str
) -> None:
    """None of these say anything about the lock's currency.

    Telling the reader to regenerate it would send them to re-resolve against
    the very index the run could not reach, so the hint must stay unprinted.
    """
    result = _run_verifier(
        tmp_path,
        _fixture(lock={"returncode": 2, "stderr": stderr}),
    )

    assert result.returncode == 1, label
    assert "FAIL uv could not verify uv.lock against pyproject.toml." in result.stderr
    assert stderr.splitlines()[0] in result.stderr
    assert "is stale" not in result.stderr
    assert "Regenerate the lock" not in result.stderr


def test_a_group_without_torch_is_rejected(tmp_path: Path) -> None:
    torchless = "-e .\nnumpy==2.5.1 ; python_version == '3.12'\n"
    result = _run_verifier(
        tmp_path,
        _fixture(cuda={"returncode": 0, "stdout": torchless}),
    )

    assert result.returncode == 1
    assert "FAIL cuda: uv.lock resolves no torch distribution" in result.stderr


def test_a_pypi_torch_in_the_rocm_group_is_rejected(tmp_path: Path) -> None:
    result = _run_verifier(
        tmp_path,
        _fixture(rocm={"returncode": 0, "stdout": _cuda_export(GOOD_CUDA_TORCH)}),
    )

    assert result.returncode == 1
    assert "FAIL rocm: expected a repo.radeon.com wheel, got:" in result.stderr


def test_the_script_requires_uv_on_path(tmp_path: Path) -> None:
    """With nothing on PATH, the missing-uv message is what the reader gets.

    The script must reach its own diagnostic before it needs any external
    command, so this points PATH at an empty directory rather than curating one
    that happens to hold the right coreutils.
    """
    empty_bin = tmp_path / "empty-bin"
    empty_bin.mkdir()
    env = dict(os.environ)
    env["PATH"] = str(empty_bin)
    process = subprocess.run(
        [BASH, str(VERIFY_TORCH_GROUPS)],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert process.returncode == 1
    assert "uv is required" in process.stderr
