#!/usr/bin/env bash
set -euo pipefail

# Reproducible ROCm/PyTorch env for AMD Ryzen AI Max / gfx1151 systems.
# Defaults follow AMD's ROCm 7.2.1 Ryzen APU guidance: Python 3.12 and
# repo.radeon.com wheels.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

has_rocm_library() {
  local dir="$1"
  [[ -d "${dir}" ]] || return 1
  compgen -G "${dir}/libroctx64.so*" >/dev/null && return 0
  compgen -G "${dir}/libamdhip64.so*" >/dev/null && return 0
  compgen -G "${dir}/libhsa-runtime64.so*" >/dev/null && return 0
  return 1
}

join_by_colon() {
  local first=1
  local value
  for value in "$@"; do
    if [[ "${first}" == "1" ]]; then
      printf '%s' "${value}"
      first=0
    else
      printf ':%s' "${value}"
    fi
  done
}

detect_rocm_library_path() {
  local roots=()
  local root
  if [[ -n "${ROCM_PATH:-}" ]]; then
    roots+=("${ROCM_PATH}")
  fi
  if command -v hipconfig >/dev/null 2>&1; then
    root="$(hipconfig --path 2>/dev/null || true)"
    if [[ -n "${root}" ]]; then
      roots+=("${root}")
    fi
  fi

  shopt -s nullglob
  roots+=(
    /opt/rocm
    /opt/rocm-*
    /opt/amdgpu
  )

  local candidates=()
  for root in "${roots[@]}"; do
    candidates+=(
      "${root}/lib"
      "${root}/lib64"
      "${root}"/core-*/lib
    )
  done

  local dirs=()
  local dir
  for dir in "${candidates[@]}"; do
    if has_rocm_library "${dir}"; then
      dirs+=("${dir}")
    fi
  done
  shopt -u nullglob

  if [[ "${#dirs[@]}" -eq 0 ]]; then
    return 1
  fi

  local deduped=()
  local seen=":"
  for dir in "${dirs[@]}"; do
    if [[ "${seen}" != *":${dir}:"* ]]; then
      deduped+=("${dir}")
      seen+="${dir}:"
    fi
  done

  join_by_colon "${deduped[@]}"
}

escape_for_double_quotes() {
  printf '%s' "$1" | sed 's/[\"\\$`]/\\&/g'
}

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is required. Install it from https://docs.astral.sh/uv/ first." >&2
  exit 1
fi

uv sync --group rocm

VENV_ABS="${REPO_ROOT}/.venv"

ROCM_LIBRARY_PATH="$(detect_rocm_library_path || true)"
if [[ -z "${ROCM_LIBRARY_PATH}" ]]; then
  echo "warning: no ROCm runtime library directory found; probe may fail" >&2
else
  export LD_LIBRARY_PATH="${ROCM_LIBRARY_PATH}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
fi

PYTHON_ROCM="${VENV_ABS}/bin/python-rocm"
ACTIVATE_ROCM="${VENV_ABS}/bin/activate-rocm"

if [[ -n "${ROCM_LIBRARY_PATH}" ]]; then
  cat > "${PYTHON_ROCM}" <<EOF
#!/usr/bin/env bash
export LD_LIBRARY_PATH="$(escape_for_double_quotes "${ROCM_LIBRARY_PATH}")\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}"
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL="\${TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL:-1}"
exec "${VENV_ABS}/bin/python" "\$@"
EOF
else
  cat > "${PYTHON_ROCM}" <<EOF
#!/usr/bin/env bash
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL="\${TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL:-1}"
exec "${VENV_ABS}/bin/python" "\$@"
EOF
fi
chmod +x "${PYTHON_ROCM}"

if [[ -n "${ROCM_LIBRARY_PATH}" ]]; then
  cat > "${ACTIVATE_ROCM}" <<EOF
# Generated by code/tools/setup_rocm_ryzen_env.sh.
source "${VENV_ABS}/bin/activate"
export LD_LIBRARY_PATH="$(escape_for_double_quotes "${ROCM_LIBRARY_PATH}")\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}"
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL="\${TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL:-1}"
EOF
else
  cat > "${ACTIVATE_ROCM}" <<EOF
# Generated by code/tools/setup_rocm_ryzen_env.sh.
source "${VENV_ABS}/bin/activate"
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL="\${TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL:-1}"
EOF
fi
chmod +x "${ACTIVATE_ROCM}"

echo "ROCm wrapper: ${PYTHON_ROCM}"
echo "ROCm activation helper: source ${ACTIVATE_ROCM}"

"${PYTHON_ROCM}" -m trec_rag.rocm_probe
